# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0eeb258916c98498e904fb5c58b891f5c54c7b903d32e4f3ef5cfb33d63808de9a54aabc05dc6de11cd9b9ec7398aa8c3af48251d9d5d895e565f325c3839238

test:
  secret_key_base: 3793fe7078bc58f6b40731f26e63ef5e5604823ad162a36946d86a02f549ac8382133f16b2ed05930678cbcdfab4cec74a788c5909f3f0c6c8f257c053f2a605

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
